[type/__ssrq_nsd_key] Check --algorithm parameter presence

diff --git a/type/__ssrq_nsd_key/manifest b/type/__ssrq_nsd_key/manifest
--- a/type/__ssrq_nsd_key/manifest
+++ b/type/__ssrq_nsd_key/manifest
@@ -26,17 +26,6 @@ NSD_KEY_DIR="${CONF_BASE_DIR}/nsd.key.d"
 key_name=${__object_id:?}
 
 state_should=$(cat "${__object:?}/parameter/state")
-algorithm=$(cat "${__object:?}/parameter/algorithm")
-
-
-# Check if the given algorithm is a supported one.
-grep -qxF "${algorithm}" <"${__object:?}/explorer/algorithms" || {
-	printf 'Unsupported or invalid --algorithm: %s\n' "${algorithm}" >&2
-	printf 'Target explorer reports the following supported algorithms:\n%s\n' \
-		"$(sed 's/^/ - /' "${__object:?}/explorer/algorithms")" >&2
-	exit 1
-}
-
 
 # Generate slug to be used in file names
 file_name_slug=$(printf '%s' "${key_name}" | tr -c 'A-Za-z0-9-.' '_' | sed 's/\.$//')
@@ -59,11 +48,26 @@ in
 		__directory "${NSD_KEY_DIR}" --state present \
 			--owner root --group "${NSD_GROUP}" --mode 0750
 
-		secret=$(cat "${__object:?}/parameter/secret")
+		secret=$(cat "${__object:?}/parameter/secret" 2>/dev/null)
 		test -n "${secret}" || {
-			echo 'Parameter --secret must be set if --state present.' >&2
+			echo 'Parameter --secret is required if --state present.' >&2
 			exit 1
 		}
+
+		algorithm=$(cat "${__object:?}/parameter/algorithm" 2>/dev/null)
+		test -n "${algorithm}" || {
+			echo 'Parameter --algorithm is required if --state present.' >&2
+			exit 1
+		}
+
+		# Check if the given algorithm is a supported one.
+		grep -qxF "${algorithm}" <"${__object:?}/explorer/algorithms" || {
+			printf 'Unsupported or invalid --algorithm: %s\n' "${algorithm}" >&2
+			printf 'Target explorer reports the following supported algorithms:\n%s\n' \
+				"$(sed 's/^/ - /' "${__object:?}/explorer/algorithms")" >&2
+			exit 1
+		}
+
 
 		export CDIST_ORDER_DEPENDENCY=true
 		# Secret file
